version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: wp_local_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
      # Mount the SQL dump to be imported automatically on first startup
      - ./u640336053_UB95s.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  wordpress:
    image: wordpress:latest
    container_name: wp_local_web
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      IS_DOCKER: "true"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_local_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
